theme: jekyll-theme-hacker
title: Crypto For Kids
description: Modern cryptography explained in language kids can understand

lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
